language: node_js
node_js:
- '4.1'
before_install:
- npm install -g istanbul gulp dependency-check
after_install:
- gulp build
script:
- dependency-check package.json && istanbul cover test/index.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage